# Generated by Django 5.1.15 on 2026-08-26 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='日付')),
                ('day_type', models.CharField(choices=[('business', '営業日'), ('company_holiday', '所定休日'), ('statutory_holiday', '法定休日')], default='business', max_length=20, verbose_name='区分')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='名称')),
            ],
            options={
                'verbose_name': '会社カレンダー',
                'verbose_name_plural': '会社カレンダー',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('break_mode', models.CharField(choices=[('auto_deduct', '自動控除'), ('punch', '実打刻')], default='auto_deduct', max_length=12, verbose_name='休憩方式')),
                ('break_rules', models.JSONField(blank=True, default=list, help_text='例: [{"over": 360, "deduct": 45}, {"over": 480, "deduct": 60}]（拘束時間の分）', verbose_name='自動控除ルール')),
                ('scheduled_minutes', models.PositiveIntegerField(default=480, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='所定労働時間（分）')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='所定始業')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='所定終業')),
                ('holiday_dow', models.JSONField(blank=True, default=list, help_text='0=日曜 … 6=土曜。例: [0, 6]', verbose_name='所定休日の曜日')),
                ('statutory_holiday_dow', models.PositiveSmallIntegerField(blank=True, help_text='0=日曜 … 6=土曜', null=True, verbose_name='法定休日の曜日')),
                ('is_default', models.BooleanField(default=False, verbose_name='新規ユーザーの初期割当')),
            ],
            options={
                'verbose_name': '勤務体系',
                'verbose_name_plural': '勤務体系',
                'ordering': ['name'],
            },
        ),
    ]
