# Generated by Django 5.1.15 on 2026-08-27 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('work_date', models.DateField(verbose_name='対象日')),
                ('requested_clock_in_at', models.DateTimeField(blank=True, null=True, verbose_name='修正後の出勤時刻')),
                ('requested_clock_out_at', models.DateTimeField(blank=True, null=True, verbose_name='修正後の退勤時刻')),
                ('reason', models.TextField(verbose_name='理由')),
                ('status', models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認済み'), ('rejected', '差し戻し')], default='pending', max_length=20, verbose_name='状態')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('rejected_reason', models.CharField(blank=True, max_length=300, verbose_name='差し戻し理由')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
            ],
            options={
                'verbose_name': '打刻修正申請',
                'verbose_name_plural': '打刻修正申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('work_date', models.DateField(verbose_name='勤務日')),
                ('clock_in_at', models.DateTimeField(blank=True, null=True, verbose_name='出勤時刻')),
                ('clock_out_at', models.DateTimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('day_type', models.CharField(choices=[('business', '営業日'), ('company_holiday', '所定休日'), ('statutory_holiday', '法定休日')], default='business', max_length=20, verbose_name='日区分')),
                ('source', models.CharField(choices=[('punch', '打刻'), ('admin_correction', '管理者修正')], default='punch', max_length=20, verbose_name='入力元')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
            ],
            options={
                'verbose_name': '打刻記録',
                'verbose_name_plural': '打刻記録',
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_minutes', models.PositiveIntegerField(default=0, verbose_name='実労働（分）')),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='休憩（分）')),
                ('overtime_within_legal', models.PositiveIntegerField(default=0, verbose_name='法定内残業（分）')),
                ('overtime_statutory', models.PositiveIntegerField(default=0, verbose_name='法定外残業（分）')),
                ('night_minutes', models.PositiveIntegerField(default=0, verbose_name='深夜労働（分）')),
                ('holiday_minutes', models.PositiveIntegerField(default=0, verbose_name='休日労働（分）')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='警告')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='計算日時')),
                ('time_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='attendance.timerecord', verbose_name='打刻記録')),
            ],
            options={
                'verbose_name': '日次集計',
                'verbose_name_plural': '日次集計',
            },
        ),
        migrations.CreateModel(
            name='BreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='休憩開始')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='休憩終了')),
                ('time_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.timerecord', verbose_name='打刻記録')),
            ],
            options={
                'verbose_name': '休憩記録',
                'verbose_name_plural': '休憩記録',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('year_month', models.CharField(help_text='YYYY-MM', max_length=7, verbose_name='対象年月')),
                ('status', models.CharField(choices=[('draft', '作成中'), ('submitted', '申請中'), ('approved', '承認済み')], default='draft', max_length=20, verbose_name='状態')),
                ('work_days', models.PositiveIntegerField(default=0, verbose_name='出勤日数')),
                ('worked_minutes', models.PositiveIntegerField(default=0, verbose_name='実労働合計（分）')),
                ('overtime_within_legal_minutes', models.PositiveIntegerField(default=0, verbose_name='法定内残業合計（分）')),
                ('overtime_statutory_minutes', models.PositiveIntegerField(default=0, verbose_name='法定外残業合計（分）')),
                ('night_minutes', models.PositiveIntegerField(default=0, verbose_name='深夜労働合計（分）')),
                ('holiday_minutes', models.PositiveIntegerField(default=0, verbose_name='休日労働合計（分）')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='申請日時')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='ロック日時')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendances', to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
            ],
            options={
                'verbose_name': '月次勤怠',
                'verbose_name_plural': '月次勤怠',
                'ordering': ['-year_month'],
                'constraints': [models.UniqueConstraint(fields=('user', 'year_month'), name='uniq_monthly_attendance_user_ym')],
            },
        ),
        migrations.AddConstraint(
            model_name='timerecord',
            constraint=models.UniqueConstraint(fields=('user', 'work_date'), name='uniq_time_record_user_date'),
        ),
    ]
