# Generated by Django 5.1.15 on 2026-08-29 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Idempotency-Key')),
                ('endpoint', models.CharField(max_length=100, verbose_name='エンドポイント')),
                ('response_status', models.PositiveSmallIntegerField(verbose_name='レスポンスステータス')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='レスポンスボディ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idempotencyキー',
                'verbose_name_plural': 'Idempotencyキー',
                'constraints': [models.UniqueConstraint(fields=('key', 'endpoint', 'user'), name='unique_idempotency_key_per_endpoint_user')],
            },
        ),
    ]
