# Generated by Django 5.1.15 on 2026-08-27 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('approval', '承認'), ('reminder', 'リマインド'), ('info', 'お知らせ')], max_length=20, verbose_name='種別')),
                ('title', models.CharField(max_length=120, verbose_name='タイトル')),
                ('body', models.CharField(blank=True, max_length=300, verbose_name='本文')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='リンク')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='既読日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='宛先')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
