# Generated by Django 5.1.15 on 2026-08-27 00:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=120, verbose_name='名前・屋号')),
                ('tax_category', models.CharField(choices=[('taxable', '課税事業者'), ('exempt', '免税事業者')], default='taxable', max_length=10, verbose_name='課税区分')),
                ('invoice_reg_no', models.CharField(blank=True, max_length=14, verbose_name='インボイス登録番号')),
                ('withholding_target', models.BooleanField(default=True, help_text='個人事業主は対象、法人は対象外', verbose_name='源泉徴収対象')),
                ('closing_day', models.PositiveSmallIntegerField(default=31, help_text='31=月末', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='締め日')),
                ('payment_month_offset', models.PositiveSmallIntegerField(default=1, help_text='0=当月 1=翌月 2=翌々月', validators=[django.core.validators.MaxValueValidator(2)], verbose_name='支払月オフセット')),
                ('payment_day', models.PositiveSmallIntegerField(default=10, help_text='31=月末', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='支払日')),
                ('bank_info', models.CharField(blank=True, max_length=200, verbose_name='振込先')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '外注先',
                'verbose_name_plural': '外注先',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractorRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('hourly', '時給制'), ('daily', '日給制'), ('fixed', '固定額制')], max_length=10, verbose_name='単価タイプ')),
                ('rate_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='単価額')),
                ('effective_from', models.DateField(verbose_name='適用開始日')),
                ('effective_to', models.DateField(blank=True, help_text='空欄は現在も有効', null=True, verbose_name='適用終了日')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='contractors.contractor', verbose_name='外注先')),
            ],
            options={
                'verbose_name': '外注単価履歴',
                'verbose_name_plural': '外注単価履歴',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ContractorClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='対象期間開始')),
                ('period_end', models.DateField(verbose_name='対象期間終了（締め日）')),
                ('payment_due_date', models.DateField(verbose_name='支払期日')),
                ('status', models.CharField(choices=[('open', '未締め'), ('closed', '締め済み'), ('invoiced', '請求書発行済み')], default='open', max_length=10, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closings', to='contractors.contractor', verbose_name='外注先')),
            ],
            options={
                'verbose_name': '外注締めサイクル',
                'verbose_name_plural': '外注締めサイクル',
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('contractor', 'period_end'), name='uniq_closing_contractor_period_end')],
            },
        ),
        migrations.CreateModel(
            name='ContractorWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('year_month', models.CharField(help_text='YYYY-MM', max_length=7, verbose_name='対象年月')),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='稼働時間')),
                ('days', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='稼働日数')),
                ('fixed_applied', models.BooleanField(default=False, verbose_name='固定額を適用')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='contractors.contractor', verbose_name='外注先')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='入力者')),
            ],
            options={
                'verbose_name': '外注稼働実績',
                'verbose_name_plural': '外注稼働実績',
                'ordering': ['-year_month'],
                'constraints': [models.UniqueConstraint(fields=('contractor', 'year_month'), name='uniq_work_record_contractor_ym')],
            },
        ),
    ]
