# Generated by Django 5.1.15 on 2026-08-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.EmailField(blank=True, help_text='請求書送信先', max_length=254, verbose_name='メールアドレス'),
        ),
    ]
