# Generated by Django 5.1.15 on 2026-08-27 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExemptDeductionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='控除割合(%)')),
                ('effective_from', models.DateField(verbose_name='適用開始日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='適用終了日')),
            ],
            options={
                'verbose_name': '免税事業者 経過措置控除率マスタ',
                'verbose_name_plural': '免税事業者 経過措置控除率マスタ',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('standard', '標準税率(10%)'), ('reduced', '軽減税率(8%)'), ('exempt', '対象外')], max_length=10, verbose_name='税率区分')),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='税率(%)')),
                ('effective_from', models.DateField(verbose_name='適用開始日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='適用終了日')),
            ],
            options={
                'verbose_name': '消費税率マスタ',
                'verbose_name_plural': '消費税率マスタ',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='WithholdingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_amount', models.DecimalField(decimal_places=0, default=1000000, max_digits=12, verbose_name='閾値')),
                ('rate_below_percent', models.DecimalField(decimal_places=2, default=10.21, max_digits=5, verbose_name='閾値以下の税率(%)')),
                ('rate_above_percent', models.DecimalField(decimal_places=2, default=20.42, max_digits=5, verbose_name='閾値超過分の税率(%)')),
                ('effective_from', models.DateField(verbose_name='適用開始日')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='適用終了日')),
            ],
            options={
                'verbose_name': '源泉徴収税率マスタ',
                'verbose_name_plural': '源泉徴収税率マスタ',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('invoice_no', models.CharField(max_length=30, unique=True, verbose_name='請求書番号')),
                ('issued_on', models.DateField(verbose_name='発行日')),
                ('period_start', models.DateField(verbose_name='対象期間開始')),
                ('period_end', models.DateField(verbose_name='対象期間終了')),
                ('tax_category', models.CharField(choices=[('standard', '標準税率(10%)'), ('reduced', '軽減税率(8%)'), ('exempt', '対象外')], max_length=10, verbose_name='税率区分')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='小計（税抜）')),
                ('tax_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='消費税額')),
                ('withholding_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='源泉徴収税額')),
                ('payable_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='差引支払額')),
                ('exempt_deduction_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='免税事業者控除率(%)')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('issued', '発行確定'), ('sent', '送信済み'), ('void', '取消（赤伝）')], default='draft', max_length=10, verbose_name='状態')),
                ('pdf_key', models.CharField(blank=True, max_length=255, verbose_name='PDFファイルキー')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contractors.contractor', verbose_name='外注先')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('void_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_by', to='billing.invoice', verbose_name='取消元')),
            ],
            options={
                'verbose_name': '請求書',
                'verbose_name_plural': '請求書',
                'ordering': ['-issued_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='通知日時')),
                ('confirm_deadline', models.DateField(verbose_name='確認期限')),
                ('confirm_method', models.CharField(default='deemed_after_deadline', help_text='期限経過で確認済とみなす', max_length=30, verbose_name='確認方法')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認日時')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='billing.invoice', verbose_name='請求書')),
            ],
            options={
                'verbose_name': '仕入明細書確認記録',
                'verbose_name_plural': '仕入明細書確認記録',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='宛先')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('status', models.CharField(choices=[('sent', '送信済み'), ('bounced', 'バウンス'), ('complained', '苦情'), ('failed', '送信失敗')], default='sent', max_length=10, verbose_name='状態')),
                ('message_id', models.CharField(blank=True, max_length=120, verbose_name='メッセージID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='billing.invoice', verbose_name='請求書')),
            ],
            options={
                'verbose_name': '請求書送信ログ',
                'verbose_name_plural': '請求書送信ログ',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='摘要')),
                ('quantity', models.DecimalField(decimal_places=1, default=1, max_digits=8, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='単価')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額')),
                ('tax_category', models.CharField(choices=[('standard', '標準税率(10%)'), ('reduced', '軽減税率(8%)'), ('exempt', '対象外')], max_length=10, verbose_name='税率区分')),
                ('withholding_applicable', models.BooleanField(default=True, verbose_name='源泉徴収対象')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice', verbose_name='請求書')),
            ],
            options={
                'verbose_name': '請求書明細',
                'verbose_name_plural': '請求書明細',
            },
        ),
        migrations.CreateModel(
            name='WithholdingStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='対象年')),
                ('total_payment', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='支払金額合計')),
                ('total_withholding', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='源泉徴収税額合計')),
                ('pdf_key', models.CharField(blank=True, max_length=255, verbose_name='PDFファイルキー')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withholding_statements', to='contractors.contractor', verbose_name='外注先')),
            ],
            options={
                'verbose_name': '支払調書',
                'verbose_name_plural': '支払調書',
                'ordering': ['-year', 'contractor__name'],
                'constraints': [models.UniqueConstraint(fields=('contractor', 'year'), name='uniq_withholding_statement_contractor_year')],
            },
        ),
    ]
