# Generated by Django 5.1.15 on 2026-08-29 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_tax_masters'),
        ('contractors', '0002_contractor_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'void'), _negated=True), fields=('contractor', 'period_end'), name='uniq_active_invoice_per_contractor_period'),
        ),
    ]
