# Generated by Django 5.1.15 on 2026-08-26 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=120, verbose_name='会社名')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('representative', models.CharField(blank=True, max_length=60, verbose_name='代表者名')),
                ('invoice_reg_no', models.CharField(blank=True, help_text='T + 13桁', max_length=14, verbose_name='インボイス登録番号')),
                ('rounding_mode', models.CharField(choices=[('floor', '切り捨て'), ('round', '四捨五入'), ('ceil', '切り上げ')], default='floor', max_length=10, verbose_name='消費税の端数処理')),
                ('logo_key', models.CharField(blank=True, max_length=255, verbose_name='ロゴのオブジェクトキー')),
            ],
            options={
                'verbose_name': '会社設定',
                'verbose_name_plural': '会社設定',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('name', models.CharField(max_length=60, verbose_name='氏名')),
                ('role', models.CharField(choices=[('admin', '管理者'), ('employee', '正社員')], default='employee', max_length=10, verbose_name='区分')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('retired_at', models.DateField(blank=True, null=True, verbose_name='退職日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Django管理サイトを使える')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('work_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='attendance.workpattern', verbose_name='勤務体系')),
            ],
            options={
                'verbose_name': '利用者',
                'verbose_name_plural': '利用者',
                'ordering': ['name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60, verbose_name='操作')),
                ('target_type', models.CharField(max_length=60, verbose_name='対象種別')),
                ('target_id', models.BigIntegerField(blank=True, null=True, verbose_name='対象ID')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='変更前')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='変更後')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '監査ログ',
                'verbose_name_plural': '監査ログ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='accounts_au_target__0c7dca_idx'), models.Index(fields=['-created_at'], name='accounts_au_created_721afe_idx')],
            },
        ),
    ]
