# Generated by Django 5.1.15 on 2026-08-27 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leave_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='leave.paidleavepolicy', verbose_name='有給ポリシー'),
        ),
    ]
