# Generated by Django 5.1.15 on 2026-08-29 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_team_user_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, verbose_name='トークンのSHA-256ハッシュ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='発行日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
            ],
            options={
                'verbose_name': 'パスワード再設定トークン',
                'verbose_name_plural': 'パスワード再設定トークン',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='accounts_pa_token_h_2771ed_idx')],
            },
        ),
    ]
