# Generated by Django 5.1.15 on 2026-08-27 00:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('is_paid', models.BooleanField(default=True, verbose_name='有給')),
                ('supports_half_day', models.BooleanField(default=False, verbose_name='半日取得可')),
                ('requires_reason', models.BooleanField(default=False, verbose_name='理由必須')),
                ('annual_limit_days', models.DecimalField(blank=True, decimal_places=1, help_text='空欄は上限なし', max_digits=5, null=True, verbose_name='年間上限日数')),
                ('requires_period', models.BooleanField(default=False, help_text='産休・育休など。ONの場合は leave_absence_period を作る', verbose_name='期間管理')),
                ('counts_toward_mandatory_five', models.BooleanField(default=False, help_text='年次有給休暇のみ ON にする', verbose_name='年5日取得義務の対象')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '休暇種類',
                'verbose_name_plural': '休暇種類',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaidLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('grant_method', models.CharField(choices=[('hire_date', '入社日基準'), ('uniform', '一斉付与')], default='hire_date', max_length=10, verbose_name='付与方式')),
                ('uniform_grant_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='一斉付与月')),
                ('uniform_grant_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='一斉付与日')),
                ('carryover_limit_days', models.DecimalField(blank=True, decimal_places=1, help_text='空欄は無制限', max_digits=5, null=True, verbose_name='繰越上限日数')),
                ('expiry_years', models.PositiveSmallIntegerField(default=2, verbose_name='失効年数')),
                ('allow_half_day', models.BooleanField(default=True, verbose_name='半日取得可')),
                ('required_attendance_rate', models.DecimalField(decimal_places=3, default=0.8, max_digits=4, verbose_name='付与に必要な出勤率')),
                ('is_default', models.BooleanField(default=False, verbose_name='新規ユーザーの初期割当')),
            ],
            options={
                'verbose_name': '有給ポリシー',
                'verbose_name_plural': '有給ポリシー',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('unit', models.CharField(choices=[('full', '全日'), ('half_am', '午前半休'), ('half_pm', '午後半休')], default='full', max_length=10, verbose_name='単位')),
                ('days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='日数')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='理由')),
                ('status', models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認済み'), ('rejected', '差し戻し'), ('cancelled', '取消')], default='pending', max_length=20, verbose_name='状態')),
                ('is_statutory_designation', models.BooleanField(default=False, help_text='年5日取得義務の会社時季指定に該当する場合 ON', verbose_name='時季指定')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('rejected_reason', models.CharField(blank=True, max_length=300, verbose_name='差し戻し理由')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype', verbose_name='休暇種類')),
            ],
            options={
                'verbose_name': '休暇申請',
                'verbose_name_plural': '休暇申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveAbsencePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了予定日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_periods', to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_periods', to='leave.leaverequest', verbose_name='関連申請')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_periods', to='leave.leavetype', verbose_name='休暇種類')),
            ],
            options={
                'verbose_name': '産休・育休等の期間',
                'verbose_name_plural': '産休・育休等の期間',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PaidLeaveGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_on', models.DateField(verbose_name='付与日')),
                ('days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='付与日数')),
                ('expires_on', models.DateField(verbose_name='失効日')),
                ('source_note', models.CharField(blank=True, max_length=120, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_leave_grants', to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='leave.paidleavepolicy', verbose_name='ポリシー')),
            ],
            options={
                'verbose_name': '有給付与ロット',
                'verbose_name_plural': '有給付与ロット',
                'ordering': ['expires_on'],
            },
        ),
        migrations.CreateModel(
            name='LeaveConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='消化日数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='leave.leaverequest', verbose_name='休暇申請')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='leave.paidleavegrant', verbose_name='付与ロット')),
            ],
            options={
                'verbose_name': '有給消化明細',
                'verbose_name_plural': '有給消化明細',
            },
        ),
        migrations.CreateModel(
            name='PaidLeaveGrantRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_of_service', models.PositiveIntegerField(verbose_name='勤続月数')),
                ('granted_days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='付与日数')),
                ('prorated_weekly_days', models.PositiveSmallIntegerField(blank=True, help_text='空欄はフルタイム', null=True, verbose_name='比例付与の週所定労働日数区分')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_rules', to='leave.paidleavepolicy', verbose_name='ポリシー')),
            ],
            options={
                'verbose_name': '有給付与テーブル',
                'verbose_name_plural': '有給付与テーブル',
                'ordering': ['policy', 'prorated_weekly_days', 'months_of_service'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'months_of_service', 'prorated_weekly_days'), name='uniq_grant_rule_policy_months_prorated')],
            },
        ),
    ]
