# Generated by Django 5.1.15 on 2026-08-27 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeLimitPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('monthly_limit_minutes', models.PositiveIntegerField(default=2700, help_text='既定45時間', verbose_name='月間上限（分）')),
                ('annual_limit_minutes', models.PositiveIntegerField(default=21600, help_text='既定360時間', verbose_name='年間上限（分）')),
                ('warning_threshold_percent', models.PositiveSmallIntegerField(default=80, verbose_name='警告閾値（％）')),
                ('special_clause_enabled', models.BooleanField(default=False, verbose_name='特別条項あり')),
                ('special_annual_limit_minutes', models.PositiveIntegerField(default=43200, help_text='既定720時間', verbose_name='特別条項時 年間上限（分）')),
                ('special_monthly_limit_minutes', models.PositiveIntegerField(default=6000, help_text='既定100時間未満', verbose_name='特別条項時 単月上限（分・未満）')),
                ('special_monthly_over_limit_max_times', models.PositiveSmallIntegerField(default=6, verbose_name='月45時間超が許される回数/年')),
                ('is_default', models.BooleanField(default=False, verbose_name='既定ポリシー')),
            ],
            options={
                'verbose_name': '36協定ポリシー',
                'verbose_name_plural': '36協定ポリシー',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('paid_leave_five_days', '年5日有給未取得'), ('overtime_monthly', '月間残業上限'), ('overtime_annual', '年間残業上限'), ('overtime_landing_forecast', '残業 着地見込み'), ('overtime_multi_month_avg', '残業 複数月平均'), ('overtime_monthly_over_count', '月45時間超の回数')], max_length=30, verbose_name='種別')),
                ('target_period', models.CharField(help_text='YYYY-MM または YYYY', max_length=10, verbose_name='対象年月/年度')),
                ('severity', models.CharField(choices=[('warning', '注意'), ('critical', '重大'), ('violation', '違反')], max_length=10, verbose_name='深刻度')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='詳細')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='検知日時')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解消日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='対象者')),
            ],
            options={
                'verbose_name': 'アラート',
                'verbose_name_plural': 'アラート',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['alert_type', 'target_period'], name='compliance__alert_t_0470e1_idx')],
            },
        ),
    ]
